server {
    listen 80;
    server_name musafir-tour-travel.duckdns.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name musafir-tour-travel.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/musafir-tour-travel.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/musafir-tour-travel.duckdns.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }
}