// Dummy data for seeding the database

export const usersData = [
  {
    username: "john_doe",
    email: "john.doe@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K", // hashed "password123"
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "jane_smith",
    email: "jane.smith@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "admin_user",
    email: "admin@musafir.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "admin",
  },
  {
    username: "mike_wilson",
    email: "mike.wilson@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "sarah_jones",
    email: "sarah.jones@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "david_brown",
    email: "david.brown@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "emily_davis",
    email: "emily.davis@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "robert_taylor",
    email: "robert.taylor@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "lisa_anderson",
    email: "lisa.anderson@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "chris_martin",
    email: "chris.martin@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "amanda_white",
    email: "amanda.white@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "james_miller",
    email: "james.miller@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "jennifer_lee",
    email: "jennifer.lee@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "thomas_garcia",
    email: "thomas.garcia@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
  {
    username: "patricia_rodriguez",
    email: "patricia.rodriguez@example.com",
    password: "$2b$10$rQ8K8K8K8K8K8K8K8K8K8O8K8K8K8K8K8K8K8K8K8K8K8K8K8K",
    profilePicture: "https://res.cloudinary.com/dpu6rveug/image/upload/v1763527341/profile-img_iq5gto.webp",
    role: "user",
  },
];

export const hotelsData = [
  {
    name: "Taj Mahal Palace",
    country: "India",
    city: "Mumbai",
    tier: "Luxury",
    pricePerNight: 15000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Deluxe Room", surcharge: 2000 },
      { name: "Suite", surcharge: 5000 },
      { name: "Presidential Suite", surcharge: 10000 },
    ],
    description: "Iconic luxury hotel overlooking the Gateway of India with world-class amenities.",
  },
  {
    name: "Oberoi Mumbai",
    country: "India",
    city: "Mumbai",
    tier: "Luxury",
    pricePerNight: 18000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Deluxe Room", surcharge: 3000 },
      { name: "Executive Suite", surcharge: 7000 },
    ],
    description: "Five-star hotel with stunning sea views and exceptional service.",
  },
  {
    name: "Burj Al Arab",
    country: "UAE",
    city: "Dubai",
    tier: "Luxury",
    pricePerNight: 25000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Deluxe Suite", surcharge: 5000 },
      { name: "Royal Suite", surcharge: 15000 },
    ],
    description: "The world's most luxurious hotel, an architectural marvel.",
  },
  {
    name: "Atlantis The Palm",
    country: "UAE",
    city: "Dubai",
    tier: "Luxury",
    pricePerNight: 20000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Deluxe Room", surcharge: 3000 },
      { name: "Underwater Suite", surcharge: 20000 },
    ],
    description: "Iconic resort with underwater suites and world-class dining.",
  },
  {
    name: "The Leela Palace",
    country: "India",
    city: "New Delhi",
    tier: "Luxury",
    pricePerNight: 12000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Deluxe Room", surcharge: 2000 },
      { name: "Royal Suite", surcharge: 8000 },
    ],
    description: "Luxurious palace hotel in the heart of New Delhi.",
  },
  {
    name: "ITC Maratha",
    country: "India",
    city: "Mumbai",
    tier: "Luxury",
    pricePerNight: 10000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Executive Room", surcharge: 1500 },
      { name: "Suite", surcharge: 4000 },
    ],
    description: "Luxury hotel with traditional Indian architecture and modern amenities.",
  },
  {
    name: "Budget Inn Mumbai",
    country: "India",
    city: "Mumbai",
    tier: "Budget",
    pricePerNight: 2000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Standard Room", surcharge: 0 },
      { name: "Deluxe Room", surcharge: 500 },
    ],
    description: "Affordable accommodation in central Mumbai.",
  },
  {
    name: "Standard Hotel Dubai",
    country: "UAE",
    city: "Dubai",
    tier: "Standard",
    pricePerNight: 5000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Standard Room", surcharge: 0 },
      { name: "Superior Room", surcharge: 1000 },
    ],
    description: "Comfortable mid-range hotel in Dubai city center.",
  },
  {
    name: "Heritage Hotel Jaipur",
    country: "India",
    city: "Jaipur",
    tier: "Standard",
    pricePerNight: 4000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Heritage Room", surcharge: 500 },
      { name: "Royal Room", surcharge: 1500 },
    ],
    description: "Beautiful heritage property showcasing Rajasthani architecture.",
  },
  {
    name: "Beach Resort Goa",
    country: "India",
    city: "Goa",
    tier: "Standard",
    pricePerNight: 6000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Beach View Room", surcharge: 1000 },
      { name: "Villa", surcharge: 3000 },
    ],
    description: "Relaxing beachfront resort with stunning ocean views.",
  },
  {
    name: "City Center Hotel",
    country: "India",
    city: "Bangalore",
    tier: "Standard",
    pricePerNight: 3500,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Standard Room", surcharge: 0 },
      { name: "Business Room", surcharge: 800 },
    ],
    description: "Convenient hotel in the heart of Bangalore.",
  },
  {
    name: "Mountain View Resort",
    country: "India",
    city: "Shimla",
    tier: "Standard",
    pricePerNight: 4500,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Mountain View Room", surcharge: 1000 },
      { name: "Cottage", surcharge: 2000 },
    ],
    description: "Scenic resort nestled in the Himalayan foothills.",
  },
  {
    name: "Desert Camp Jaisalmer",
    country: "India",
    city: "Jaisalmer",
    tier: "Budget",
    pricePerNight: 3000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Tent", surcharge: 0 },
      { name: "Deluxe Tent", surcharge: 500 },
    ],
    description: "Authentic desert camping experience in the Thar Desert.",
  },
  {
    name: "Backpacker Hostel",
    country: "India",
    city: "Mumbai",
    tier: "Budget",
    pricePerNight: 800,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Dorm Bed", surcharge: 0 },
      { name: "Private Room", surcharge: 500 },
    ],
    description: "Budget-friendly hostel for backpackers and solo travelers.",
  },
  {
    name: "Luxury Resort Maldives",
    country: "Maldives",
    city: "Malé",
    tier: "Luxury",
    pricePerNight: 30000,
    images: [
      "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    ],
    roomTypes: [
      { name: "Water Villa", surcharge: 10000 },
      { name: "Presidential Villa", surcharge: 25000 },
    ],
    description: "Exclusive overwater villas with direct lagoon access.",
  },
];

export const locationsData = [
  {
    name: "Gateway of India",
    country: "India",
    city: "Mumbai",
    details: "Historical arch landmark facing the Arabian Sea. Popular tourist site and symbol of Mumbai.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Marine Drive",
    country: "India",
    city: "Mumbai",
    details: "Scenic boulevard along the coast, known as the Queen's Necklace for its curved shape and lights.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Elephanta Caves",
    country: "India",
    city: "Mumbai",
    details: "Ancient rock-cut cave temples dedicated to Lord Shiva, a UNESCO World Heritage Site.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 2,
  },
  {
    name: "Burj Khalifa",
    country: "UAE",
    city: "Dubai",
    details: "World's tallest building with incredible skyline view from the observation deck.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Palm Jumeirah",
    country: "UAE",
    city: "Dubai",
    details: "Man-made island shaped like a palm tree, home to luxury resorts and residences.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 2,
  },
  {
    name: "Dubai Mall",
    country: "UAE",
    city: "Dubai",
    details: "One of the world's largest shopping malls with over 1,200 stores and entertainment options.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 3,
  },
  {
    name: "Red Fort",
    country: "India",
    city: "New Delhi",
    details: "Historic fort built by Mughal emperor Shah Jahan, a UNESCO World Heritage Site.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "India Gate",
    country: "India",
    city: "New Delhi",
    details: "War memorial arch dedicated to Indian soldiers who died in World War I.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Qutub Minar",
    country: "India",
    city: "New Delhi",
    details: "Tallest brick minaret in the world, built in the 12th century.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 2,
  },
  {
    name: "Amber Fort",
    country: "India",
    city: "Jaipur",
    details: "Magnificent fort palace with stunning architecture and panoramic views of the city.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Hawa Mahal",
    country: "India",
    city: "Jaipur",
    details: "Palace of Winds, a five-story palace with 953 windows for royal women to observe street festivals.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 2,
  },
  {
    name: "Calangute Beach",
    country: "India",
    city: "Goa",
    details: "Famous beach known for water sports, shacks, and vibrant nightlife.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Basilica of Bom Jesus",
    country: "India",
    city: "Goa",
    details: "Historic church housing the mortal remains of St. Francis Xavier, a UNESCO World Heritage Site.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 2,
  },
  {
    name: "Jaisalmer Fort",
    country: "India",
    city: "Jaisalmer",
    details: "Living fort with shops, hotels, and ancient havelis, known as the Golden Fort.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 1,
  },
  {
    name: "Thar Desert",
    country: "India",
    city: "Jaisalmer",
    details: "Vast desert offering camel safaris, desert camping, and stunning sunset views.",
    locationImage: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
    day: 2,
  },
];

export const foodOptionsData = [
  {
    name: "Breakfast Only",
    surchargePerDay: 0,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
    ],
    description: "Daily breakfast included in your stay.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Half Board",
    surchargePerDay: 500,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Dinner", surcharge: 500 },
    ],
    description: "Breakfast and dinner included daily.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Full Board",
    surchargePerDay: 1000,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 400 },
      { name: "Dinner", surcharge: 600 },
    ],
    description: "All three meals included - breakfast, lunch, and dinner.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "All Inclusive",
    surchargePerDay: 2000,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 600 },
      { name: "Dinner", surcharge: 800 },
    ],
    description: "All meals plus snacks and beverages included.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Premium Dining",
    surchargePerDay: 3000,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 1000 },
      { name: "Dinner", surcharge: 1500 },
    ],
    description: "Gourmet meals at premium restaurants with fine dining experience.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Vegetarian Plan",
    surchargePerDay: 800,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 300 },
      { name: "Dinner", surcharge: 500 },
    ],
    description: "Complete vegetarian meal plan with traditional and international options.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Vegan Plan",
    surchargePerDay: 900,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 350 },
      { name: "Dinner", surcharge: 550 },
    ],
    description: "Plant-based meal plan with vegan-friendly options.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Halal Plan",
    surchargePerDay: 1000,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 400 },
      { name: "Dinner", surcharge: 600 },
    ],
    description: "Halal-certified meals prepared according to Islamic dietary laws.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Jain Meal Plan",
    surchargePerDay: 850,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 320 },
      { name: "Dinner", surcharge: 530 },
    ],
    description: "Jain-friendly meals without root vegetables, prepared with care.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Kids Meal Plan",
    surchargePerDay: 600,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 250 },
      { name: "Dinner", surcharge: 350 },
    ],
    description: "Specially designed meals for children with kid-friendly options.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Gluten-Free Plan",
    surchargePerDay: 950,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 380 },
      { name: "Dinner", surcharge: 570 },
    ],
    description: "Gluten-free meals for guests with celiac disease or gluten sensitivity.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Low-Carb Plan",
    surchargePerDay: 1100,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 450 },
      { name: "Dinner", surcharge: 650 },
    ],
    description: "Low-carbohydrate meal plan for health-conscious travelers.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Keto Plan",
    surchargePerDay: 1200,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 500 },
      { name: "Dinner", surcharge: 700 },
    ],
    description: "Ketogenic diet meal plan with high-fat, low-carb options.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Diabetic-Friendly Plan",
    surchargePerDay: 1000,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 400 },
      { name: "Dinner", surcharge: 600 },
    ],
    description: "Meal plan designed for guests with diabetes, with controlled sugar content.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
  {
    name: "Seafood Lovers",
    surchargePerDay: 2500,
    foodOptions: [
      { name: "Breakfast", surcharge: 0 },
      { name: "Lunch", surcharge: 900 },
      { name: "Dinner", surcharge: 1200 },
    ],
    description: "Premium seafood-focused meal plan with fresh catches daily.",
    image: "https://res.cloudinary.com/dpu6rveug/image/upload/v1759671196/Screenshot_2025-10-05_190108_mxt8nl.png",
  },
];


